### PR TITLE
Minesweeper Example

### PR DESCRIPTION
**Pull request by Mitch4018169**
This contains a minesweeper example for minecraft utilising mcpp

### CODE REVIEW

**Comment by rozukke** [comment]
Sorry for the delay, will get to a proper check on this tomorrow as I've been doing heavy work for a different project.

**Review by rozukke — DISMISSED** [review]
Great work, thank you for the contribution!

**Comment by rozukke** [comment]
Seems like the formatter is failing, run `clang-format` with the style file available at the repo root.

**Comment by Mitch4018169** [comment]
I am currently working on cleaning up the code and using better practices, I'll let you know when I am done and its good to merge

**Comment by Mitch4018169** [comment]
I've added all the functions I wish to add to this.
It is ready to be reviewed.

**Pull request merged**
